---
- name: Install Git
  hosts: all
  become: yes
  tasks:
    - name: Update the package index
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present
